-- ============================================================
-- Vihok AI — Supabase Schema
-- วิธีใช้: Supabase Dashboard → SQL Editor → วางทั้งหมด → RUN
-- สร้างตารางที่ backend/db.py ใช้งาน (conversations, memories)
-- ============================================================

-- ตารางแชท (conversations)
CREATE TABLE IF NOT EXISTS public.conversations (
  id         TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL DEFAULT 'anon',
  title      TEXT,
  messages   JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ถ้ามีตารางเดิมอยู่แล้ว (เช่นสร้างจาก Supabase Table Editor)
-- ให้เพิ่มคอลัมน์ที่ขาดให้ครบ
ALTER TABLE public.conversations
  ADD COLUMN IF NOT EXISTS messages JSONB NOT NULL DEFAULT '[]'::jsonb;

-- ตารางความจำ (memories)
CREATE TABLE IF NOT EXISTS public.memories (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   TEXT NOT NULL DEFAULT 'anon',
  question  TEXT,
  answer    TEXT,
  saved_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index สำหรับ query ที่ backend ใช้
CREATE INDEX IF NOT EXISTS idx_conversations_user_created
  ON public.conversations (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_memories_user_saved
  ON public.memories (user_id, saved_at DESC);
