import type { UILocale } from "@/lib/locale"

/** ข้อความ landing สาธารณะ 5 ภาษา — ชุดเดียวกับเพจภายใน (ไทย default) */
export const HOME_COPY: Record<UILocale, Record<string, string>> = {
  th: {
    badge: "vihokai.com - เหนือชั้นแบบนก",
    h1a: "เหนือชั้น",
    h1b: "แบบนก",
    sub1: "ถามครั้งเดียว",
    sub2: "ได้ 5 คำตอบพร้อมกัน",
    sub3: "จากมุมสูง",
    sub4: "Meta AI เป็นเหยี่ยวตัดสิน Best Answer ใน 3 วิ - เร็วกว่า Perplexity 3x",
    ctaFree: "เริ่มบินฟรี 55 ครั้ง →",
    ctaHow: "ดูวิธีบิน",
    noAccount: "ยังไม่มีบัญชี?",
    signupFree: "สมัครฟรี",
    hasAccount: "มีแล้ว",
    login: "เข้าสู่ระบบ",
    loginNav: "Log in",
    signupNav: "Sign up →",
    enterChat: "เข้าแชท →",
    freeNote: "แผนฟรี 55 ครั้ง รีเซ็ตใหม่ทุก 6 ชั่วโมง",
    feat1t: "มองกว้างแบบเหยี่ยว",
    feat1d: "ถามครั้งเดียว 5 AIs ตอบพร้อมกัน เห็นทุกมุม",
    feat2t: "เร็วแบบโฉบ",
    feat2d: "Groq + Llama 3.3 400 tokens/sec เร็วกว่า 3x",
    feat3t: "ตัดสินแบบจ่าฝูง",
    feat3d: "Meta AI Judge สรุปคำตอบที่ดีที่สุดให้",
    pricingH: "บินฟรี แล้วค่อยบินสูง",
    freeName: "นกกระจอก",
    freeSub: "Free — 55 ครั้ง / 6 ชม.",
    freeCta: "เริ่มบินฟรี",
    freeF1: "เทียบ 2 AIs",
    freeF2: "Judge 5 ครั้ง",
    freeF3: "รีเซ็ตใหม่ทุก 6 ชั่วโมง",
    proBadge: "🔥 รอเปิดตัว",
    proName: "เหยี่ยว",
    proSub: "Pro — รอ Kola / Wari ติดตั้ง",
    proCta: "แจ้งเตือนเมื่อเปิด",
    proF1: "เทียบ 5 AIs ไม่จำกัด",
    proF2: "Judge 500 ครั้ง",
    proF3: "Research 8 บท",
    proF4: "เร็ว 400 tok/s",
    teamName: "พญาอินทรี",
    teamSub: "Team — รอ Kola / Wari ติดตั้ง",
    teamCta: "ติดต่อทีมงาน",
    teamF1: "ทุกอย่างใน Pro",
    teamF2: "Team + API",
    teamF3: "White-label",
    perMo: "/mo",
    footer: "© 2026 ViHok AI - www.vihokai.com | เหนือชั้นแบบนก 🦅 Soar Above",
  },
  en: {
    badge: "vihokai.com - Soar Above",
    h1a: "Soar",
    h1b: "Above",
    sub1: "Ask once,",
    sub2: "get 5 answers at once",
    sub3: "from above",
    sub4: "Meta AI judges the Best Answer in 3s — 3x faster than Perplexity",
    ctaFree: "Start free — 55 chats →",
    ctaHow: "How it flies",
    noAccount: "No account yet?",
    signupFree: "Sign up free",
    hasAccount: "Have one?",
    login: "Log in",
    loginNav: "Log in",
    signupNav: "Sign up →",
    enterChat: "Open chat →",
    freeNote: "Free plan: 55 chats, resets every 6 hours",
    feat1t: "Eagle-eye view",
    feat1d: "Ask once — 5 AIs answer together, every angle",
    feat2t: "Swoop-fast",
    feat2d: "Groq + Llama 3.3 at 400 tokens/sec, 3x faster",
    feat3t: "Alpha verdict",
    feat3d: "Meta AI Judge picks the best answer",
    pricingH: "Fly free, then fly higher",
    freeName: "Sparrow",
    freeSub: "Free — 55 chats / 6 hrs",
    freeCta: "Start free",
    freeF1: "Compare 2 AIs",
    freeF2: "5 Judge calls",
    freeF3: "Resets every 6 hours",
    proBadge: "🔥 Coming soon",
    proName: "Hawk",
    proSub: "Pro — pending Kola / Wari setup",
    proCta: "Notify me",
    proF1: "Unlimited 5-AI compare",
    proF2: "500 Judge calls",
    proF3: "8 research reports",
    proF4: "400 tok/s",
    teamName: "Eagle",
    teamSub: "Team — pending Kola / Wari setup",
    teamCta: "Contact us",
    teamF1: "Everything in Pro",
    teamF2: "Team + API",
    teamF3: "White-label",
    perMo: "/mo",
    footer: "© 2026 ViHok AI - www.vihokai.com | Soar Above 🦅",
  },
  zh: {
    badge: "vihokai.com - 翱翔天际",
    h1a: "翱翔",
    h1b: "天际",
    sub1: "一次提问，",
    sub2: "同时获得 5 个答案",
    sub3: "高瞻远瞩",
    sub4: "Meta AI 3 秒判定最佳答案 — 比 Perplexity 快 3 倍",
    ctaFree: "免费开始 55 次 →",
    ctaHow: "了解原理",
    noAccount: "还没有账号？",
    signupFree: "免费注册",
    hasAccount: "已有账号？",
    login: "登录",
    loginNav: "Log in",
    signupNav: "Sign up →",
    enterChat: "进入聊天 →",
    freeNote: "免费版 55 次，每 6 小时重置",
    feat1t: "鹰眼视角",
    feat1d: "一次提问，5 个 AI 同时回答",
    feat2t: "俯冲般快速",
    feat2d: "Groq + Llama 3.3 每秒 400 tokens，快 3 倍",
    feat3t: "头领裁决",
    feat3d: "Meta AI Judge 选出最佳答案",
    pricingH: "免费起飞，再飞更高",
    freeName: "麻雀",
    freeSub: "Free — 每 6 小时 55 次",
    freeCta: "免费开始",
    freeF1: "对比 2 个 AI",
    freeF2: "Judge 5 次",
    freeF3: "每 6 小时重置",
    proBadge: "🔥 即将上线",
    proName: "猎鹰",
    proSub: "Pro — 等待 Kola / Wari 接入",
    proCta: "上线提醒我",
    proF1: "5 AI 对比不限次",
    proF2: "Judge 500 次",
    proF3: "8 篇研究报告",
    proF4: "400 tok/s",
    teamName: "金雕",
    teamSub: "Team — 等待 Kola / Wari 接入",
    teamCta: "联系我们",
    teamF1: "Pro 全部功能",
    teamF2: "Team + API",
    teamF3: "白标",
    perMo: "/mo",
    footer: "© 2026 ViHok AI - www.vihokai.com | 翱翔天际 🦅",
  },
  ja: {
    badge: "vihokai.com - 高く舞う",
    h1a: "高く",
    h1b: "舞う",
    sub1: "一度の質問で、",
    sub2: "5 つの回答を同時に",
    sub3: "上空から",
    sub4: "Meta AI が 3 秒でベストアンサーを判定 — Perplexity の 3 倍速",
    ctaFree: "無料で開始 55 回 →",
    ctaHow: "仕組みを見る",
    noAccount: "アカウントなし？",
    signupFree: "無料登録",
    hasAccount: "お持ちの方",
    login: "ログイン",
    loginNav: "Log in",
    signupNav: "Sign up →",
    enterChat: "チャットへ →",
    freeNote: "無料プラン 55 回、6 時間ごとにリセット",
    feat1t: "鷹の目",
    feat1d: "一度の質問に 5 つの AI が同時回答",
    feat2t: "急降下の速さ",
    feat2d: "Groq + Llama 3.3 毎秒 400 トークン、3 倍速",
    feat3t: "群れの判定",
    feat3d: "Meta AI Judge が最良回答を選定",
    pricingH: "無料で飛び、さらに高く",
    freeName: "スズメ",
    freeSub: "Free — 6 時間ごとに 55 回",
    freeCta: "無料で開始",
    freeF1: "2 AI 比較",
    freeF2: "Judge 5 回",
    freeF3: "6 時間ごとにリセット",
    proBadge: "🔥 近日公開",
    proName: "タカ",
    proSub: "Pro — Kola / Wari 導入待ち",
    proCta: "通知を受け取る",
    proF1: "5 AI 比較 無制限",
    proF2: "Judge 500 回",
    proF3: "リサーチ 8 件",
    proF4: "400 tok/s",
    teamName: "イヌワシ",
    teamSub: "Team — Kola / Wari 導入待ち",
    teamCta: "お問い合わせ",
    teamF1: "Pro の全機能",
    teamF2: "Team + API",
    teamF3: "ホワイトラベル",
    perMo: "/mo",
    footer: "© 2026 ViHok AI - www.vihokai.com | 高く舞う 🦅",
  },
  ko: {
    badge: "vihokai.com - 높이 날다",
    h1a: "높이",
    h1b: "날다",
    sub1: "한 번의 질문으로",
    sub2: "5 개의 답변을 동시에",
    sub3: "상공에서",
    sub4: "Meta AI 가 3 초 만에 베스트 답변 판정 — Perplexity 보다 3 배 빠름",
    ctaFree: "무료 시작 55 회 →",
    ctaHow: "원리 보기",
    noAccount: "계정이 없으신가요?",
    signupFree: "무료 가입",
    hasAccount: "이미 계정이 있나요?",
    login: "로그인",
    loginNav: "Log in",
    signupNav: "Sign up →",
    enterChat: "채팅 열기 →",
    freeNote: "무료 플랜 55 회, 6 시간마다 초기화",
    feat1t: "매의 눈",
    feat1d: "한 번의 질문에 5 개 AI 가 동시 답변",
    feat2t: "급강하 속도",
    feat2d: "Groq + Llama 3.3 초당 400 토큰, 3 배 빠름",
    feat3t: "무리의 판정",
    feat3d: "Meta AI Judge 가 최적 답변 선정",
    pricingH: "무료로 날고, 더 높이",
    freeName: "참새",
    freeSub: "Free — 6 시간마다 55 회",
    freeCta: "무료 시작",
    freeF1: "2 개 AI 비교",
    freeF2: "Judge 5 회",
    freeF3: "6 시간마다 초기화",
    proBadge: "🔥 출시 예정",
    proName: "매",
    proSub: "Pro — Kola / Wari 도입 대기",
    proCta: "알림 받기",
    proF1: "5 AI 비교 무제한",
    proF2: "Judge 500 회",
    proF3: "리서치 8 건",
    proF4: "400 tok/s",
    teamName: "독수리",
    teamSub: "Team — Kola / Wari 도입 대기",
    teamCta: "문의하기",
    teamF1: "Pro 전체 기능",
    teamF2: "Team + API",
    teamF3: "화이트라벨",
    perMo: "/mo",
    footer: "© 2026 ViHok AI - www.vihokai.com | 높이 날다 🦅",
  },
}
