import type { UILocale } from "@/lib/locale"

/** ข้อความ landing Kola (VihokAI 1.0) 5 ภาษา — ใช้ locale เดียวกับเพจแชท */
export const HOME_COPY: Record<UILocale, Record<string, string>> = {
  th: {
    navFeatures: "Features",
    navTeam: "AI Team",
    navMission: "How it works",
    navPricing: "Pricing",
    navRoadmap: "Roadmap",
    loginNav: "Log in",
    signupNav: "Sign up →",
    enterChat: "เข้าแชท →",
    heroBadge: "vihokai.com — AI COMMANDER",
    heroTitle1: "VihokAI",
    heroTitle2: "1.0",
    heroTitle3: "Kola",
    tagA: "One command.",
    tagB: "An entire AI team.",
    heroDesc:
      "VihokAI ให้ AI หลายตัวทำงานร่วมกัน โดยมี Kola เป็นผู้ควบคุมภารกิจ เลือก AI ที่เหมาะกับงาน ค้นหา วิเคราะห์ เขียนโค้ด และตรวจสอบคำตอบก่อนส่งกลับให้คุณ",
    ctaFree: "Start free",
    ctaHow: "See how Kola works",
    freePlan: "Free plan",
    freeChats: "55 chats",
    freeReset: "resets every 6 hours",
    freeNote: "แผนฟรี 55 ครั้ง รีเซ็ตใหม่ทุก 6 ชั่วโมง",
    noAccount: "ยังไม่มีบัญชี?",
    signupFree: "สมัครฟรี",
    hasAccount: "มีแล้ว",
    login: "เข้าสู่ระบบ",
    fMulti: "หลายโมเดล",
    fSearch: "ข้อมูลล่าสุด",
    fRag: "เอกสารของคุณ",
    fCode: "สร้างและแก้โค้ด",
    fReason: "คิดวิเคราะห์",
    fAuto: "ทำงานอัตโนมัติ",
    teamEyebrow: "THE KOLA AI TEAM",
    teamH: "Kola ไม่ได้ทำงานคนเดียว",
    teamSub: "Kola ทำหน้าที่เป็น Orchestrator แล้วเลือก AI ที่เหมาะที่สุดสำหรับแต่ละภารกิจ",
    teamLead: "Muse Spark 1.3",
    teamLeadD: "จัดทีม • Memory • Judge",
    teamR: "Compound Mini",
    teamRD: "Web • Search • Research",
    teamC: "DeepSeek V3",
    teamCD: "Code • API • Debug",
    teamD: "Qwen3 8B",
    teamDD: "PDF • RAG • Summary",
    teamB: "Qwen Local",
    teamBD: "Cache • Simple Tasks",
    mEyebrow: "HOW KOLA THINKS",
    mH1: "Ask once.",
    mH2: "Kola handles the rest.",
    mDesc:
      "ไม่ต้องเลือกโมเดลเอง Kola วิเคราะห์โจทย์ แยกภารกิจ ส่งงานให้ AI แต่ละตัว แล้วตรวจสอบผลลัพธ์ก่อนรวมเป็นคำตอบสุดท้าย",
    mCta: "Try Kola",
    mReq: "วิเคราะห์ PDF + เขียน API + หาข้อมูลล่าสุด",
    pEyebrow: "SIMPLE AI PRICING",
    pH1: "AI ที่เก่งขึ้น",
    pH2: "ไม่จำเป็นต้องแพงขึ้น",
    pSub: "Kola เลือกโมเดลตามความเหมาะสมของงาน เพื่อลดต้นทุนและรักษาคุณภาพของคำตอบ",
    freeName: "นกกระจอก",
    freeSub: "Free — 55 ครั้ง / 6 ชม.",
    freeCta: "เริ่มบินฟรี",
    freeF1: "เทียบ 2 AIs",
    freeF2: "Judge 5 ครั้ง",
    freeF3: "รีเซ็ตใหม่ทุก 6 ชั่วโมง",
    proBadge: "🔥 รอเปิดตัว",
    proName: "เหยี่ยว",
    proSub: "Pro — รอ Kola / Wari ติดตั้ง",
    proCta: "แจ้งเตือนเมื่อเปิด",
    proF1: "เทียบ 5 AIs ไม่จำกัด",
    proF2: "Judge 500 ครั้ง",
    proF3: "Research 8 บท",
    perMo: "/mo",
    ctaH1: "Ready to",
    ctaH2: "Soar Above?",
    ctaSub: "เริ่มต้นกับ VihokAI 1.0 Kola และให้ AI Team ทำงานร่วมกันแทนคุณ",
    ctaTry: "Try Kola",
    footerSub: "VihokAI 1.0 Kola • AI Team Intelligence",
  },
  en: {
    navFeatures: "Features",
    navTeam: "AI Team",
    navMission: "How it works",
    navPricing: "Pricing",
    navRoadmap: "Roadmap",
    loginNav: "Log in",
    signupNav: "Sign up →",
    enterChat: "Open chat →",
    heroBadge: "vihokai.com — AI COMMANDER",
    heroTitle1: "VihokAI",
    heroTitle2: "1.0",
    heroTitle3: "Kola",
    tagA: "One command.",
    tagB: "An entire AI team.",
    heroDesc:
      "VihokAI runs multiple AIs as one team, with Kola commanding the mission — picking the right AI, searching, analyzing, coding, and verifying before answering you.",
    ctaFree: "Start free",
    ctaHow: "See how Kola works",
    freePlan: "Free plan",
    freeChats: "55 chats",
    freeReset: "resets every 6 hours",
    freeNote: "Free plan: 55 chats, resets every 6 hours",
    noAccount: "No account yet?",
    signupFree: "Sign up free",
    hasAccount: "Have one?",
    login: "Log in",
    fMulti: "Multi-model",
    fSearch: "Fresh data",
    fRag: "Your docs",
    fCode: "Build & fix code",
    fReason: "Reasoning",
    fAuto: "Automation",
    teamEyebrow: "THE KOLA AI TEAM",
    teamH: "Kola never works alone",
    teamSub: "Kola acts as the Orchestrator, picking the best AI for each mission.",
    teamLead: "Muse Spark 1.3",
    teamLeadD: "Team • Memory • Judge",
    teamR: "Compound Mini",
    teamRD: "Web • Search • Research",
    teamC: "DeepSeek V3",
    teamCD: "Code • API • Debug",
    teamD: "Qwen3 8B",
    teamDD: "PDF • RAG • Summary",
    teamB: "Qwen Local",
    teamBD: "Cache • Simple Tasks",
    mEyebrow: "HOW KOLA THINKS",
    mH1: "Ask once.",
    mH2: "Kola handles the rest.",
    mDesc:
      "No need to pick models yourself. Kola analyzes the task, splits the mission, assigns each AI, then verifies results into one final answer.",
    mCta: "Try Kola",
    mReq: "Analyze PDF + write API + find latest data",
    pEyebrow: "SIMPLE AI PRICING",
    pH1: "Smarter AI",
    pH2: "doesn't have to cost more",
    pSub: "Kola routes each job to the right model — lower cost, same quality answers.",
    freeName: "Sparrow",
    freeSub: "Free — 55 chats / 6 hrs",
    freeCta: "Start free",
    freeF1: "Compare 2 AIs",
    freeF2: "5 Judge calls",
    freeF3: "Resets every 6 hours",
    proBadge: "🔥 Coming soon",
    proName: "Hawk",
    proSub: "Pro — pending Kola / Wari setup",
    proCta: "Notify me",
    proF1: "Unlimited 5-AI compare",
    proF2: "500 Judge calls",
    proF3: "8 research reports",
    perMo: "/mo",
    ctaH1: "Ready to",
    ctaH2: "Soar Above?",
    ctaSub: "Start with VihokAI 1.0 Kola and let the AI Team work for you.",
    ctaTry: "Try Kola",
    footerSub: "VihokAI 1.0 Kola • AI Team Intelligence",
  },
  zh: {
    navFeatures: "功能",
    navTeam: "AI 团队",
    navMission: "工作原理",
    navPricing: "价格",
    navRoadmap: "路线图",
    loginNav: "登录",
    signupNav: "注册 →",
    enterChat: "进入聊天 →",
    heroBadge: "vihokai.com — AI 指挥官",
    heroTitle1: "VihokAI",
    heroTitle2: "1.0",
    heroTitle3: "Kola",
    tagA: "一条指令。",
    tagB: "一整个 AI 团队。",
    heroDesc:
      "VihokAI 让多个 AI 协同工作，由 Kola 指挥任务——选择合适的 AI、搜索、分析、写代码，并在回复前核验答案。",
    ctaFree: "免费开始",
    ctaHow: "了解 Kola 原理",
    freePlan: "免费版",
    freeChats: "55 次对话",
    freeReset: "每 6 小时重置",
    freeNote: "免费版 55 次，每 6 小时重置",
    noAccount: "还没有账号？",
    signupFree: "免费注册",
    hasAccount: "已有账号？",
    login: "登录",
    fMulti: "多模型",
    fSearch: "最新数据",
    fRag: "你的文档",
    fCode: "编写修复代码",
    fReason: "推理分析",
    fAuto: "自动执行",
    teamEyebrow: "KOLA AI 团队",
    teamH: "Kola 从不独自工作",
    teamSub: "Kola 担任 orchestrator，为每个任务挑选最合适的 AI。",
    teamLead: "Muse Spark 1.3",
    teamLeadD: "组队 • 记忆 • 裁决",
    teamR: "Compound Mini",
    teamRD: "网页 • 搜索 • 研究",
    teamC: "DeepSeek V3",
    teamCD: "代码 • API • 调试",
    teamD: "Qwen3 8B",
    teamDD: "PDF • RAG • 总结",
    teamB: "Qwen Local",
    teamBD: "缓存 • 简单任务",
    mEyebrow: "KOLA 的思考方式",
    mH1: "提问一次。",
    mH2: "其余交给 Kola。",
    mDesc: "无需自己选模型。Kola 分析任务、拆分使命、分配 AI，最后核验结果并汇总成最终答案。",
    mCta: "试试 Kola",
    mReq: "分析 PDF + 编写 API + 查找最新数据",
    pEyebrow: "简单 AI 定价",
    pH1: "更强的 AI",
    pH2: "不必更贵",
    pSub: "Kola 按任务匹配模型——降低成本，保持回答质量。",
    freeName: "麻雀",
    freeSub: "免费 — 每 6 小时 55 次",
    freeCta: "免费开始",
    freeF1: "对比 2 个 AI",
    freeF2: "Judge 5 次",
    freeF3: "每 6 小时重置",
    proBadge: "🔥 即将上线",
    proName: "猎鹰",
    proSub: "Pro — 等待 Kola / Wari 接入",
    proCta: "上线提醒我",
    proF1: "5 AI 对比不限次",
    proF2: "Judge 500 次",
    proF3: "8 篇研究报告",
    perMo: "/mo",
    ctaH1: "准备好",
    ctaH2: "翱翔天际？",
    ctaSub: "从 VihokAI 1.0 Kola 开始，让 AI 团队为你工作。",
    ctaTry: "试试 Kola",
    footerSub: "VihokAI 1.0 Kola • AI 团队智能",
  },
  ja: {
    navFeatures: "機能",
    navTeam: "AI チーム",
    navMission: "仕組み",
    navPricing: "料金",
    navRoadmap: "ロードマップ",
    loginNav: "ログイン",
    signupNav: "登録 →",
    enterChat: "チャットへ →",
    heroBadge: "vihokai.com — AI コマンダー",
    heroTitle1: "VihokAI",
    heroTitle2: "1.0",
    heroTitle3: "Kola",
    tagA: "ワンコマンド。",
    tagB: "AI チーム全体。",
    heroDesc:
      "VihokAI は複数の AI を一つのチームとして動かし、Kola が任務を指揮——最適な AI を選び、検索・分析・コーディングし、回答前に検証します。",
    ctaFree: "無料で開始",
    ctaHow: "Kola の仕組み",
    freePlan: "無料プラン",
    freeChats: "55 チャット",
    freeReset: "6 時間ごとにリセット",
    freeNote: "無料プラン 55 回、6 時間ごとにリセット",
    noAccount: "アカウントなし？",
    signupFree: "無料登録",
    hasAccount: "お持ちの方",
    login: "ログイン",
    fMulti: "マルチモデル",
    fSearch: "最新データ",
    fRag: "あなたの文書",
    fCode: "コード作成修正",
    fReason: "推論",
    fAuto: "自動化",
    teamEyebrow: "THE KOLA AI TEAM",
    teamH: "Kola は一人で働かない",
    teamSub: "Kola はオーケストレーターとして、各任務に最適な AI を選びます。",
    teamLead: "Muse Spark 1.3",
    teamLeadD: "編成 • メモリ • 判定",
    teamR: "Compound Mini",
    teamRD: "Web • 検索 • 調査",
    teamC: "DeepSeek V3",
    teamCD: "コード • API • デバッグ",
    teamD: "Qwen3 8B",
    teamDD: "PDF • RAG • 要約",
    teamB: "Qwen Local",
    teamBD: "キャッシュ • 簡易タスク",
    mEyebrow: "KOLA の思考",
    mH1: "一度聞けば。",
    mH2: "あとは Kola が。",
    mDesc:
      "モデル選びは不要。Kola が課題を分析し、任務を分割して各 AI に割当て、結果を検証して最終回答にまとめます。",
    mCta: "Kola を試す",
    mReq: "PDF 分析 + API 作成 + 最新情報の調査",
    pEyebrow: "シンプルな AI 料金",
    pH1: "賢い AI",
    pH2: "高くなくていい",
    pSub: "Kola が仕事ごとに最適モデルを選択——コストを下げ、回答品質を維持。",
    freeName: "スズメ",
    freeSub: "無料 — 6 時間ごとに 55 回",
    freeCta: "無料で開始",
    freeF1: "2 AI 比較",
    freeF2: "Judge 5 回",
    freeF3: "6 時間ごとにリセット",
    proBadge: "🔥 近日公開",
    proName: "タカ",
    proSub: "Pro — Kola / Wari 導入待ち",
    proCta: "通知を受け取る",
    proF1: "5 AI 比較 無制限",
    proF2: "Judge 500 回",
    proF3: "リサーチ 8 件",
    perMo: "/mo",
    ctaH1: "Ready to",
    ctaH2: "Soar Above?",
    ctaSub: "VihokAI 1.0 Kola から始めて、AI チームに働いてもらいましょう。",
    ctaTry: "Kola を試す",
    footerSub: "VihokAI 1.0 Kola • AI チームインテリジェンス",
  },
  ko: {
    navFeatures: "기능",
    navTeam: "AI 팀",
    navMission: "원리",
    navPricing: "요금",
    navRoadmap: "로드맵",
    loginNav: "로그인",
    signupNav: "가입 →",
    enterChat: "채팅 열기 →",
    heroBadge: "vihokai.com — AI 커맨더",
    heroTitle1: "VihokAI",
    heroTitle2: "1.0",
    heroTitle3: "Kola",
    tagA: "하나의 명령.",
    tagB: "AI 팀 전체.",
    heroDesc:
      "VihokAI 는 여러 AI 를 하나의 팀으로 움직이고 Kola 가 미션을 지휘——적합한 AI 선택, 검색, 분석, 코딩 후 답변 전 검증합니다.",
    ctaFree: "무료 시작",
    ctaHow: "Kola 원리 보기",
    freePlan: "무료 플랜",
    freeChats: "55 채팅",
    freeReset: "6 시간마다 초기화",
    freeNote: "무료 플랜 55 회, 6 시간마다 초기화",
    noAccount: "계정이 없으신가요?",
    signupFree: "무료 가입",
    hasAccount: "이미 계정이 있나요?",
    login: "로그인",
    fMulti: "멀티모델",
    fSearch: "최신 데이터",
    fRag: "내 문서",
    fCode: "코드 작성수정",
    fReason: "추론",
    fAuto: "자동화",
    teamEyebrow: "THE KOLA AI TEAM",
    teamH: "Kola 는 혼자 일하지 않는다",
    teamSub: "Kola 는 오케스트레이터로서 각 미션에 최적의 AI 를 고릅니다.",
    teamLead: "Muse Spark 1.3",
    teamLeadD: "편성 • 메모리 • 판정",
    teamR: "Compound Mini",
    teamRD: "웹 • 검색 • 리서치",
    teamC: "DeepSeek V3",
    teamCD: "코드 • API • 디버그",
    teamD: "Qwen3 8B",
    teamDD: "PDF • RAG • 요약",
    teamB: "Qwen Local",
    teamBD: "캐시 • 단순 작업",
    mEyebrow: "KOLA 의 사고",
    mH1: "한 번 물으면.",
    mH2: "나머지는 Kola 가.",
    mDesc:
      "모델을 고를 필요 없음. Kola 가 과제를 분석하고 미션을 나눠 각 AI 에 배정, 결과를 검증해 최종 답변으로 묶습니다.",
    mCta: "Kola 체험",
    mReq: "PDF 분석 + API 작성 + 최신 정보 조사",
    pEyebrow: "심플한 AI 요금",
    pH1: "똑똑한 AI",
    pH2: "비쌀 필요 없다",
    pSub: "Kola 가 작업마다 최적 모델을 선택——비용은 낮추고 답변 품질은 유지.",
    freeName: "참새",
    freeSub: "무료 — 6 시간마다 55 회",
    freeCta: "무료 시작",
    freeF1: "2 개 AI 비교",
    freeF2: "Judge 5 회",
    freeF3: "6 시간마다 초기화",
    proBadge: "🔥 출시 예정",
    proName: "매",
    proSub: "Pro — Kola / Wari 도입 대기",
    proCta: "알림 받기",
    proF1: "5 AI 비교 무제한",
    proF2: "Judge 500 회",
    proF3: "리서치 8 건",
    perMo: "/mo",
    ctaH1: "Ready to",
    ctaH2: "Soar Above?",
    ctaSub: "VihokAI 1.0 Kola 로 시작하고 AI 팀에게 맡기세요.",
    ctaTry: "Kola 체험",
    footerSub: "VihokAI 1.0 Kola • AI 팀 인텔리전스",
  },
}
